export const FAVE_TOKEN_MINT = "JCJcYgehYPRFTAwdYp5UQcyAHYcAT33C6WWWS4iFjrgx";
export const FAVE_PROGRAM_ID = "3qqA8JTRKQ28AZmqzs9bqSonsJGJjybaTdChKV1HneeU";
export const PROTOCOL_TREASURY = "D9P8Uqmxvtg9mr16GGFA2z7fFwWBYKuDMFpDYioiVFbt";
export const NETWORK = "mainnet-beta";
export const FAVE_TOTAL_SUPPLY = 100_000_000;
export const FAVE_DECIMALS = 6;
export const EXPLORER_BASE = "https://explorer.solana.com";
export const SOLSCAN_TOKEN = `https://solscan.io/token/${FAVE_TOKEN_MINT}`;
export const EXPLORER_TOKEN = `https://explorer.solana.com/address/${FAVE_TOKEN_MINT}`;
export const EXPLORER_TX = (tx: string) => `https://explorer.solana.com/tx/${tx}`;
export const EXPLORER_ADDRESS = (addr: string) => `https://explorer.solana.com/address/${addr}`;
